<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.shortthirdman.primekit</groupId>
  <artifactId>primekit-essentials</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>PrimeKit Essentials</name>
  <url>https://www.github.com/shortthirdman-org/PrimeKit</url>
  <inceptionYear>2025</inceptionYear>

  <properties>
	<isCI>true</isCI>
	<github.repository>shortthirdman-org/PrimeKit</github.repository>
    <java.version>[11,24)</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	<maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <maven.compiler.release>21</maven.compiler.release>
	<lombok.version>1.18.32</lombok.version>
	<jjwt.version>0.12.6</jjwt.version>
	<springframework.version>6.2.5</springframework.version>
	<spring-data.version>3.2.5</spring-data.version>
	<fasterxml-jackson.version>2.18.4</fasterxml-jackson.version>
	<jakarta.xml-bind.version>4.0.2</jakarta.xml-bind.version>
	<postgresql.version>42.</postgresql.version>
	<hibernate.version>5.6.10.Final</hibernate.version>
	<junit.version>5.12.0</junit.version>
	<resilience4j.version>2.3.0</resilience4j.version>
	<guava.version>32.1.3-jre</guava.version>
	<postgresql.version>42.7.3</postgresql.version>
	<junit-jupiter.version>5.10.2</junit-jupiter.version>
	<assertj.version>3.19.0</assertj.version>
  </properties>
  
  <developers>
    <developer>
      <id>author</id>
      <name>Swetank Mohanty</name>
      <email>swetank.mohanty@outlook.com</email>
      <organization>ShortThirdMan</organization>
      <timezone>UTC+530</timezone>
      <roles>
        <role>Product Owner</role>
      </roles>
    </developer>
  </developers>

  <contributors>
    <contributor>
      <name>Swetank Mohanty</name>
      <email>swetank.mohanty@outlook.com</email>
      <organization>ShortThirdMan</organization>
      <timezone>UTC+530</timezone>
    </contributor>
  </contributors>

  <licenses>
    <license>
      <name>The Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>
  
  <distributionManagement>
	<repository>
      <id>github</id>
      <name>GitHub Packages</name>
      <url>https://maven.pkg.github.com/${github.repository}</url>
    </repository>
  </distributionManagement>
  
  <scm>
	<developerConnection>scm:git:https://github.com/shortthirdman/PrimeKit.git</developerConnection>
	<tag>HEAD</tag>
  </scm>

  <dependencyManagement>
    <dependencies>
	  <dependency>
		<groupId>org.springframework</groupId>
		<artifactId>spring-framework-bom</artifactId>
		<version>${springframework.version}</version>
		<type>pom</type>
		<scope>import</scope>
	  </dependency>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${junit.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
		<groupId>jakarta.annotation</groupId>
		<artifactId>jakarta.annotation-api</artifactId>
		<version>3.0.0</version>
	</dependency>
	<dependency>
		<groupId>jakarta.xml.bind</groupId>
		<artifactId>jakarta.xml.bind-api</artifactId>
		<version>${jakarta.xml-bind.version}</version>
	</dependency>
	<dependency>
	  <groupId>org.springframework</groupId>
	  <artifactId>spring-core</artifactId>
	  <version>${springframework.version}</version>
	</dependency>
	<dependency>
	  <groupId>org.springframework</groupId>
	  <artifactId>spring-beans</artifactId>
	  <version>${springframework.version}</version>
	</dependency>
	<dependency>
	  <groupId>org.springframework</groupId>
	  <artifactId>spring-webmvc</artifactId>
	  <version>${springframework.version}</version>
	</dependency>
	<dependency>
	  <groupId>org.springframework</groupId>
	  <artifactId>spring-aop</artifactId>
	  <version>${springframework.version}</version>
	</dependency>
	<dependency>
	  <groupId>org.springframework</groupId>
	  <artifactId>spring-context-support</artifactId>
	  <version>${springframework.version}</version>
	</dependency>
	<dependency>
	  <groupId>org.springframework.security</groupId>
	  <artifactId>spring-security-core</artifactId>
	  <version>${springframework.version}</version>
	</dependency>
	<dependency>
	  <groupId>org.springframework</groupId>
	  <artifactId>spring-context</artifactId>
	  <version>${springframework.version}</version>
	</dependency>
	<dependency>
	  <groupId>org.springframework</groupId>
	  <artifactId>spring-web</artifactId>
	  <version>${springframework.version}</version>
	</dependency>
	<dependency>
	  <groupId>org.springframework</groupId>
	  <artifactId>spring-jpa</artifactId>
	  <version>2.0.8</version>
	</dependency>
	
	<dependency>
	  <groupId>org.springframework.data</groupId>
	  <artifactId>spring-data-jpa</artifactId>
	  <version>${spring-data.version}</version>
	</dependency>
	  <dependency>
	  <groupId>org.springframework.data</groupId>
	  <artifactId>spring-data-commons</artifactId>
	  <version>${spring-data.version}</version>
	</dependency>

	<dependency>
	  <groupId>io.github.resilience4j</groupId>
	  <artifactId>resilience4j-circuitbreaker</artifactId>
	  <version>${resilience4j.version}</version>
	  <optional>true</optional>
	</dependency>
	<dependency>
	  <groupId>com.google.guava</groupId>
	  <artifactId>guava</artifactId>
	  <version>${guava.version}</version>
	</dependency>
	
	<dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>${postgresql.version}</version>
	  <scope>provided</scope>
	</dependency>
	
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
      <version>1.15</version>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.11.0</version>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-core</artifactId>
      <version>${hibernate.version}</version>
    </dependency>
	<dependency>
	  <groupId>org.hibernate.common</groupId>
	  <artifactId>hibernate-commons-annotations</artifactId>
		<version>5.1.2.Final</version>
	</dependency>
	<dependency>
	  <groupId>jakarta.persistence</groupId>
	  <artifactId>jakarta.persistence-api</artifactId>
	  <version>3.2.0-M2</version>
	</dependency>
	
	<dependency>
	  <groupId>io.jsonwebtoken</groupId>
	  <artifactId>jjwt-api</artifactId>
	  <version>${jjwt.version}</version>
	</dependency>
	<dependency>
	  <groupId>io.jsonwebtoken</groupId>
	  <artifactId>jjwt-impl</artifactId>
	  <version>${jjwt.version}</version>
	  <scope>runtime</scope>
	</dependency>
	
	<dependency>
	  <groupId>com.fasterxml.jackson.core</groupId>
	  <artifactId>jackson-core</artifactId>
	  <version>${fasterxml-jackson.version}</version>
	</dependency>
	<dependency>
	  <groupId>com.fasterxml.jackson.core</groupId>
	  <artifactId>jackson-annotations</artifactId>
	  <version>${fasterxml-jackson.version}</version>
	</dependency>
	<dependency>
	  <groupId>com.fasterxml.jackson.core</groupId>
	  <artifactId>jackson-databind</artifactId>
	  <version>${fasterxml-jackson.version}</version>
	</dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.12.0</version>
    </dependency>
	<dependency>
		<groupId>org.projectlombok</groupId>
		<artifactId>lombok</artifactId>
		<version>${lombok.version}</version>
		<optional>true</optional>
    </dependency>
	
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>${assertj.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- Optionally: parameterized tests support -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <scope>test</scope>
    </dependency>
	<dependency>
	  <groupId>org.junit.jupiter</groupId>
	  <artifactId>junit-jupiter-engine</artifactId>
	  <!-- <version>${junit-jupiter.version}</version> -->
	  <scope>test</scope>
	</dependency>
	<dependency>
	  <groupId>org.junit.platform</groupId>
	  <artifactId>junit-platform-runner</artifactId>
	  <version>1.10.2</version>
	  <scope>test</scope>
	</dependency>
	<dependency>
	  <groupId>org.junit.platform</groupId>
	  <artifactId>junit-platform-suite-engine</artifactId>
	  <version>1.9.1</version>
	  <scope>test</scope>
	</dependency>
  </dependencies>

  <build>
    <finalName>primekit-essentials-${project.version}</finalName>
	<plugins>
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.3.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.13.0</version>
		  <configuration>
            <fork>false</fork>
		    <encoding>UTF-8</encoding>
		    <source>${java.version}</source>
		    <target>${java.version}</target>
			<annotationProcessorPaths>
				<path>
					<groupId>org.projectlombok</groupId>
					<artifactId>lombok</artifactId>
					<version>${lombok.version}</version>
				</path>
			</annotationProcessorPaths>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.3.0</version>
		  <configuration>
            <printSummary>true</printSummary>
			<forkCount>1</forkCount>
			<encoding>${project.build.sourceEncoding}</encoding>
			<reportFormat>brief</reportFormat>
			<testFailureIgnore>true</testFailureIgnore>
			<properties>
			<configurationParameters>
				junit.jupiter.conditions.deactivate = *
				junit.jupiter.extensions.autodetection.enabled = true
				junit.jupiter.testinstance.lifecycle.default = per_class
				junit.jupiter.execution.parallel.enabled = true
			</configurationParameters>
		  </properties>
          </configuration>
		  <dependencies>
			<dependency>
			  <groupId>me.fabriciorby</groupId>
			  <artifactId>maven-surefire-junit5-tree-reporter</artifactId>
			  <version>1.2.1</version>
			</dependency>
			<dependency>
			  <groupId>org.apache.maven.surefire</groupId>
			  <artifactId>surefire-junit-platform</artifactId>
			  <version>3.0.0</version>
			</dependency>
          </dependencies>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.4.2</version>
		  <configuration>
            <forceCreation>true</forceCreation>
            <detail>true</detail>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>3.1.2</version>
        </plugin>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-failsafe-plugin</artifactId>
			<version>3.5.3</version>
			<configuration>
				<failIfNoSpecifiedTests>true</failIfNoSpecifiedTests>
				<testFailureIgnore>true</testFailureIgnore>
			</configuration>
		</plugin>
		<plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <version>3.2.1</version>
			<configuration>
				<finalName>primekit-essentials-${project.version}</finalName>
				<attach>true</attach>
<!--				<outputDirectory>${project.build.directory}/generated-sources</outputDirectory>-->
				<outputTimestamp>${build.timestamp}</outputTimestamp>
			</configuration>
            <executions>
              <execution>
                <id>attach-sources</id>
				<phase>install</phase>
                <goals>
                  <goal>jar-no-fork</goal>
				  <goal>test-jar-no-fork</goal>
                </goals>
              </execution>
            </executions>
        </plugin>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-release-plugin</artifactId>
			<version>3.0.1</version>
			<configuration>
				<tagNameFormat>v@{project.version}</tagNameFormat>
				<checkModificationExcludes>
					<checkModificationExclude>pom.xml</checkModificationExclude>
				</checkModificationExcludes>
				<pushChanges>false</pushChanges>
				<localCheckout>true</localCheckout>
				<goals>deploy</goals>
			</configuration>
        </plugin>
		<plugin>
			<groupId>se.bjurr.gitchangelog</groupId>
			<artifactId>git-changelog-maven-plugin</artifactId>
			<version>2.2.0</version>
			<executions>
				<execution>
					<id>GenerateGitChangelog</id>
					<phase>generate-sources</phase>
					<goals>
						<goal>semantic-version</goal>
						<goal>git-changelog</goal>
					</goals>
					<configuration>
						<templateFile>changelog.mustache</templateFile>
						<prependToFile>true</prependToFile>
						<readableTagName>-([^-]+?)$</readableTagName>
						<file>CHANGELOG.md</file>
						<skip>${isCI}</skip>
						<!--<updatePomWithCurrentSemanticVersionSuffixSnapshot>false</updatePomWithCurrentSemanticVersionSuffixSnapshot>
						<updatePomWithCurrentSemanticVersionSuffixSnapshotIfNotTagged>true</updatePomWithCurrentSemanticVersionSuffixSnapshotIfNotTagged>
						<semanticMajorVersionPattern>^[Bb]reaking</semanticMajorVersionPattern>
						<semanticMinorVersionPattern>[Ff]eature</semanticMinorVersionPattern>
						<semanticPatchVersionPattern>[Ff]ix</semanticPatchVersionPattern>-->
					</configuration>
				</execution>
			</executions>
        </plugin>
	</plugins>
  </build>
</project>
