primekit.countrylayer.base-url=https://api.countrylayer.com/v2
primekit.countrylayer.all-countries=${countrylayer.base-url}/all
primekit.countrylayer.name=${countrylayer.base-url}/name/
primekit.countrylayer.capital=${countrylayer.base-url}/capital/
primekit.countrylayer.language=${countrylayer.base-url}/language/
primekit.countrylayer.currency=${countrylayer.base-url}/currency/
primekit.countrylayer.region=${countrylayer.base-url}/region/{region}
primekit.countrylayer.region-block=${countrylayer.base-url}/regionalbloc/
primekit.countrylayer.calling-code=${countrylayer.base-url}/callingcode/
primekit.countrylayer.alpha-code=${countrylayer.base-url}/alpha/
