primekit.restcountries.base-url=https://restcountries.com/v3.1
primekit.restcountries.all-countries=${primekit.restcountries.base-url}/all
primekit.restcountries.name=${primekit.restcountries.base-url}/name/
primekit.restcountries.capital=${primekit.restcountries.base-url}/capital/
primekit.restcountries.language=${primekit.restcountries.base-url}/language/
primekit.restcountries.currency=${primekit.restcountries.base-url}/currency/
primekit.restcountries.region=${primekit.restcountries.base-url}/region/{region}
primekit.restcountries.region-block=${primekit.restcountries.base-url}/regionalbloc/
primekit.restcountries.calling-code=${primekit.restcountries.base-url}/callingcode/
primekit.restcountries.alpha-code=${primekit.restcountries.base-url}/alpha/